### ISSUE TITLE
1/7/2020 Remaining ToDo (in order of priority)

### ISSUE THREAD

**Issue by real-ian** [real-social-media/frontend#1]
- [x] Remove description entirely from Albums
- [x] A user should be able to swipe right/left on posts in the news feed which are inside an album to see other posts. If the Album has > 4 posts, show the first 4 on a carousel, then on the last slide, show the album art with a "View More" button. Tapping "View More" should open the album in the user profile. When tapping the right half of the screen to skip to the next post on the news feed, the next post should be centered in the middle of the screen, even if it’s smaller (square). For example, currently when going up (tapping the left half of the screen), I have to move my thumb up to the top left once I hit a square image in order to continue jumping up. 
- [x] Tapping anywhere on the right side of the news feed that isn’t a button should skip to the next post. For example, tapping the bottom right corner (where a thumb feels at rest) should skip as it does on Snapchat. 
- [x] Tapping anywhere on the right side of the news feed that isn’t a button should skip to the next post. For example, tapping the bottom right corner (where a thumb feels at rest) should skip as it does on Snapchat. 
- [x] (Bug) When first opening the app and going to my user profile, I can’t tap settings or any posts until I scroll down. 
- [x] Add the ability for the poster (only the person who made the post) to see the total view count on the bottom right of a post. Tapping this should bring up the list of who viewed the post. This list should be in order of alphabet. The tile of this list should be "Total Views" with subtext "Views are ordered alphabetically."
- [ ] Add expires in x hours time below the post title when viewing story.
- [x] Finish comments support.
- [x] add a refresh option for now to the user profile screen (drag up to refresh)
- [x] Can't see captions in Dark themes (Green & Black). Caption text is black, on a black background. 
- [x] Change all users theme to green & black. Set green & black as default for all new users.
- [x] If > 1 “liked first by” ( > 1 like) then hide the like button on posts in the news feed for followers, since someone has already liked the post.
- [x] Build Tagging users functionality (in post caption) 
- [x] Frozen camera bug, iOS camera is fine but our camera is frozen sometimes. Switching to the iOS camera and then back to our camera unfreezes it. 
- [x] Add option to "Allow Sharing" to the create / edit post screen. This should set the backend post property "allow_sharing". If allow_sharing is disabled, no users/followers (aside from those tagged), should be able to see the share icon on that post or the share option in the post dropdown menu. 
- [x] If you are tagged in a post, you should see an option to “Repost” in the share menu & you should see the share icon regardless of it's "allow_sharing" value. "Repost" should download & repost the native quality photo.
- [x] Swipe left while viewing trending post fullscreen, or viewing a post/album should go back.
- [x] On the create/edit post screen, Rename the toggle for enable/disable "Likes" to "First Like". The description below the label should be "See the first user to like your post."
- [x] People think their post didn't upload because they can't see it in the news feed after uploading. Please add it back to appear immediately in the news feed after post upload hits 100%. This is leading to people uploading posts multiple times.
- [ ] Store IOS_OTA_VERSION, IOS_APP_STORE_VERSION in a file in S3. **This version file should be checked by the UI every 12 hours**. When the users current version is < the version in that file, either trigger OTA, or if it's the IOS app store version available which is newer, show the user an error "Please update REAL to continue", after tapping OK, the user should be taken to the app store. If the user goes back to our app without updating, they should see the same error. They should not be able to use our app. If the users current version >= IOS_OTA_VERSION && IOS_APP_STORE_VERSION, allow them to use the app. This will help for testing in beta & staging. The OTA check is also important, as users will never close our app or signout. **iOS was designed so you never have to sign out or close apps**. Many of my friends don't even know there is a way to close apps.
- [x] Add loading icon to search page. Currently users don't know to wait in order to see trending posts.
- [x] Add unique loading icons **on each post** when viewing a users profile which is shown before the thumbnail is rendered. Currently it is just black until the thumbnail appears. On slow internet connections, it's very hard to tell when you can see all of a users posts. 
- [x] Increase the loading icon time for login with google. Currently the loading icon stops before the login happens, so the user ends up pressing "login with google" a 2nd time, and logging in again. If the user knows to wait, they end up being logged in after about 7-12 seconds on the first attempt. 
- [x] Tapping "Liked first by" should take the user to a new page which explains how likes work on REAL. This page should have the title, "REAL likes", with the description: "On REAL, we don't want you to feel like you need likes. It's our goal to keep you mentally healthy. For that reason, nobody can see a posts total likes, or who liked it, aside from the first person to like the post." Tapping the users username, (tapping the username of the first user to like the post) should open that users profile.
- [x] Tapping the right half of a post in the news feed should skip to the next post, auto scrolling down to center the next picture down the news feed. This will make it faster for users to scroll through their news feed, similar to tik tok or snapchat. It will also help given that will will have fullscreen portrait posts. Please make sure this does not break pinch & zoom functionality down the road.
- [x] Tapping the left half of a post in the news feed should go back to the previous post, auto scrolling up to center the previous post.

- [x] Portrait Crop should support the full device size (it’s too small). Users should be able to post full sized photos from instagram or snapchat without being forced to crop. 

- [ ] "Expires in a day/month etc..." should be replaced with the following: If the post expires in <24 hours, it should say "Expires in x hours". If the post expires in 24 hours, it should say "Expires in a day". If the post expires in > 24 hours, it should say "Expires in x days".
- [x] After tapping a post to view it fullscreen it says "Photo" as the title. It should say "Post". 
- [x] Tapping "See more posts like this" scrolls the user up for some reason. It should scroll the user down to see more posts. 

- [ ] pinch & zoom + it should download the native quality after the user zooms, to replace it with the photo mid zoom once the download completes. 

- [ ] Add delete option to archived posts, currently users can only “restore from archived” but can’t delete until they restore. 

- [x] The “Other” button currently in the post drop down should instead be inside the share screen below “share to Instagram”. Pressing other inside the share menu should open the native iOS share menu to share to another app.

- [x] Share to Instagram says “all good the post has been saved”. It should instead show no popup, after the user shares his post to instagram successfully. 

- [x] Change new user default theme to green & black instead of red & black.
- [ ] Add the option to share to real from the iOS photos app
- [x] Change language icon should be a flag 
- [x] Should be able to view my own story in the news feed. Currently, even if I have a story, I see "+" icon on the top right of the news feed, which opens the camera when tapped.
- [x] Implement REAL Albums https://github.com/real-social-media/frontend/issues/9
- [x] Swipe left while viewing trending post fullscreen, or viewing a post/album should go back.
- [x] Build REAL comments.
- [ ] Video post support. You should be able to select videos in the iOS library, hold the camera button in the in-app camera to take a video, or switch to the mode in the in-app camera which says "Video".
- [ ] Clicking like on a trending post doesn’t work. 
- [x] Add the users username to the watermark on "shared" photos. Under "REAL" should be the users username on a new line. This should all remain very small on high resolution photos, and only legible when a user zooms in. Important: If a post has the post property origional_post_uuid set, then the username shown in the watermark should be the username of the original poster, not the current user.
- [x] Remove the "remove watermark" option from the share page.
- [x] Evaluate all linked libraries open source licenses to ensure everything we use is LGPL or does not require copyleft & allows us to sell our software commercially for profit. Copyleft meaning, we are required to make our project open source under the same exact license as that open source project. LGPL (Lesser) does not require copyleft & clears us for commercial use (for example).
- [x] Rename "Portrait" camera label to "Rectangle". This way there will be "Rectangle" which is default, and "Square". People are thinking portrait means we modify lighting (similar to iOS portrait camera which uses filters to modify lighting in select areas around your face). 
- [x] In post verification, replace text "promote products which they don’t actually use" with "promote products that they don’t actually use". 
- [x] In Payout, replace text “The Math” with “Is Calculated:” along with a semicolon instead of period.
- [x] In Payout, replace text "throughout the day & is calculated in realtime by our platform learning from the previous day's views & revenues." with "throughout the day and is calculated in real time by our platform learning from the previous day's views and revenues."
- [x] In Payout, replace “The amount of money has earned” with "The amount of money earned"
In Payout, replace "business. (e.g Apple Pay, AWS)" with "business (e.g Apple Pay, AWS)."
In Payout, replace "The total post views over the past 30 days from REAL Diamond members of posts created by other REAL Diamond members" with "Total views over the past 30 days of diamond member posts by other REAL diamond members"
- [x] Add above "It has/uses a filter" a new bullet to "Post Verification". This bullet should say "It was taken using iOS portrait mode (selective lighting/filter)."
- [x] Rename "Public Account" toggle to say "Private Account". True = private, false = public.
- [x] Rename "Change Details" in the settings screen to say "Edit Profile"
- [x] Rename "Profile Edit" title in the edit profile screen to say "Edit Profile"
- [x] Add mirror (duplicates) of all privacy & mental health settings, to the "Edit Profile" page. These should sync with the state of the settings in the other menu. For example, a user should be able to enable/disable private account, comments, likes, etc... all from either the edit profile sub menu, or the privacy & mental health sub menu. Changing the setting in one place should update it in the other.
- [x] Rename "Privacy & Mental Health" to "Mental Health & Privacy Settings".
- [x] Remove grey “verified watermark” from the share post page. The "Remove/add watermark" is enough.  
- [x] The post duration slider should have labels (tick marks), 
Day (Story), Week, Month, Forever 
With footer “All posts will become stories when they are 24 hours from expiring”. All of this should be in the translations file 

- [x] Default the camera to "Photo" instead of square

- [x] Add cropping to choose profile photo in settings, to choose profile photo in signup, and to upload photo from library in the camera.

- [x] Make "Failed Verification - Learn More" red in color, to help it stand out.

- [x] Change default camera & crop to “photo”

- [x] font color for failed verification should be always red. Currently it turns green if my theme is green, depending on the theme

- [ ] when viewing a profile, it either says "Seems to be empty" or it's blank for 3 seconds until the images appear. **We need a loading icon to instantly appear** when viewing profiles. In testing i've watched people quickly go to someones profile, then back to the news feed, thinking that person has no posts. 
https://user-images.githubusercontent.com/3436464/71771929-65539e00-2ef7-11ea-9ca3-e6171e42a263.png

- [x] Change pending verification to say "Failed Verification" + "Learn More" 

- [x] Add to new bullet to the top of the "Post Verification" learn more page:
"It's been modified, cropped, or rotated by another app"

- [x] Change "You are currently being paid" to "You will be paid x dollars per view from other diamond members" 

- [x] Add bullet to the top of the Post Verification page which says "It's been copied or was taken using another camera" 

- [x] Change "Nobody can see this status aside from you" to say "Nobody can detect if you have post verification disabled."

- [x] (Bug) tapping “see more posts like this” does nothing. 

- [x] (Bug) Profile pictures in stories are still blurry (not downloading 1080p quality). 1/1/2020 10.0.5.128
https://user-images.githubusercontent.com/3436464/71641198-5d240600-2c4c-11ea-8dca-9a13df70bfbb.png

- [x] (Bug), profile pictures on the both the user profile page and the user story icons are either super blurry or they are black forever (even after waiting 30+ minutes). 
https://user-images.githubusercontent.com/3436464/71645733-83b86000-2c91-11ea-98c4-a2c9c25456ef.png (1/1/2019 / 1.0.5.128)

- [x] Mental health settings for Views, Likes, Comments, verification, etc... should all set the default value of the individual post settings. For example, if a user has likes enabled in his mental health settings, all posts should have likes enabled by default in the "create post" page.

- [ ] Create front-end deployment script which updates the translations file & deploys a new translations file with the filename as the MD5 of the file. The new front-end should now point to this filename. (This will allow older versions of the front-end to use older translations files). It would also be great to have the front-end swap key-values for all languages which don't match en. now on when I (Ian), edit the local file, I will "find & replace all" swap the key / value for all languages. Because we will have a versioned file, this shouldn't break older versions of the UI. This will all become super important as we grow to support other languages & multiple people are collaborating on the translations github. 

- [x] Update image caching to be multithreaded & go image by image, first downloading the thumbnail quality for that first image, then the high quality version of that image. There should be two/three threads, one for downloading thumbnails sequentially, one for downloading 1080p for images sequentially, and possibly one for downloading native quality images. Native quality images should only be queued / downloaded on-demand if the user tries to pinch & zoom or save / share the image. 

- [x] Image caching for **1080p & native quality should run an MD5 check (or some other check) to ensure the file is not corrupt.** I still occasionally get corrupted downloads which are cached & never repair. Although it has become very rare 1/1/2020 10.0.5.128
https://user-images.githubusercontent.com/3436464/71641179-251cc300-2c4c-11ea-971a-6508f33d0e05.png

- [x] Switched “liked by x and y others” to say “Liked by x and many others”

- [x] Switch post settings & Privacy & Mental health settings to iOS toggles. During testing, people are confused what's enabled/disabled. Toggles with "On"/"Off" (translation file), are something nearly every tester requested. 
https://user-images.githubusercontent.com/3436464/71771830-faee2e00-2ef5-11ea-80ed-93a4af5263e1.png

- [x] Users are still confused how to create stories. We need to move the "Post Will Be Available" dropdown, to a slider which is always visible without entering a sub-menu. This slider should say beneath it "All posts will eventually become stories 24 hours before they expire". 

- [x] Add “Other” button to the bottom of the share menu which opens the iOS share menu. If the user does not want to save to photos, or upload to instagram, this "Other" button will open the native iOS share screen which allows the user to tap any app which supports images (or use airdrop etc...).

- [x] Add select profile photo from iOS photo library to the end of the signup flow. On the select a photo screen there should be a title "Choose a profile picture", with subtext "Please select a high quality photo which has not been doctored or modified in any way.". The user should then be forced to crop this photo to a square since we only want square profile photos.

- [x] "Pending Verification" along with "You are currently being paid $0.11 per view from other diamond members" & the "Post Verifications" page are both not present in the translations file or github. Please add them to the translations repo so I can update/change them. 

- [x] Add “Clear Cache” button below sign out in settings (with a trash bin 🗑 icon) , which clears any and all stored data, and restarts the app. The user should be fully logged out and nothing should be saved. 

- [ ] (Bug) - Users logging in with google for the first time after installing our app, must press "Login with Google", complete the google login flow, are taken back to the login screen, must tap "Login with Google" a 2nd time, they then see a loading icon next to the "Login with Google" button, and are taken into our app. It should all happen in one tap. Note: I had to tap "Login With Google" 5x, and select my email 5x before it worked recently, on a new device. 

- [x] Posts in the news feed should download sequentially (not all at once like they do today). Posts should download at least 10 posts ahead of where the user is (as the user scrolls). Currently our app feels horrible for new users after after signing up, because users are waiting to download all images from content@real.app before they can even see a single post on the news feed.

 - [x] Captions & bios should iOS autocorrect, new lines & emoji’s. We should also limit posts to a max of 5 newlines, so users don't break 255 char limit. **if possible, we should look into supporting markdown (github/reddit text formatting language). This would be a massive improvement over instagram, as users would be able to do anything they can do on github.**

- [x] (Bug) Edit caption takes me to the share post screen. After changing the caption, I should be taken back out of the edit caption screen. 

- [ ] Center image preview on the "Post Preview" page, and allow users to drag the corners to crop the image. Below the bottom right of the preview, there should also be a square / portrait icon, which snaps the corners to crop the image in that format while keeping the image center. All images should default the crop to the full image size, centered. Cropping an image should keep the original image unmodified in the iOS photo library & not save the rotated image to camera roll, unless the user later decides to download it.

- [ ] Allow users to rotate images in the "Post Preview" page. Rotating should be a slider, so users can rotate the image any desired amount down to the degree. Rotating an image should keep the original image unmodified in the iOS photo library & not save the rotated image to camera roll, unless the user later decides to download it.

- [x] (Bug) - Can't un-archive photos

- [x] (Bug) Swiping up / down on photo in the profile page (whole full screen viewing profile photo) should close it. 

- [x] Can’t get rid of failed uploads stuck at 0% 
https://user-images.githubusercontent.com/3436464/71396202-249a8180-25e7-11ea-97c6-93a0fce29335.png

- [ ] Add Apple Pay (get diamond) button. https://docs.google.com/document/d/185EGRcI6aPHQvjGqN12InVzRZOqp1ofVkCswswGcfwg/edit?usp=sharing

- [ ] Restrict diamond only features to diamond members only https://docs.google.com/document/d/1JpUly9gC0zZirDC7-Ny0HHhmszMDyc5AI7Ikcd1QCOs/edit?usp=sharing

- [ ] (Feature) Profile link (e.g real.app/username) in any web browser should open our app to that user profile. 

- [ ] (Feature) Post link (e.g real.app/username/post_id) in any web browser should open our app to that user profile.

- [ ] (Feature) Add "Copy Link" to share post options. It should copy the post URL (above) to the iOS clipboard.

- [ ] (Feature) Add "Share Link" to share post options. Tapping this should open the native iOS menu with share options for sharing text (link).

- [ ] (Bug) Fix animation when dragging up/down stories to close them. Currently drag up causes a drap from left to right closing animation. 

- [x] Bug - there is no way to get back to trending posts after viewing trending users (without closing and opening the app$ 

- [ ] Swiping up in camera (while the camera is open) should also open photo library to import a photo 

- [ ] (bug) Fix duplicate Signup issue. Content@real.app was created multiple times across user pool & identity pools when using reset password for a user who came from google.

- [x] Every time I open my profile, the images are being re downloaded fully (I see thumbnail first). They should be cached for the news feed & the users profile. 
If the native format is downloaded because the user ever tried to share the photo or pinch & zoom, the native quality should be cached and always shown in the news feed/profile. So they don't need to redownload the native quality to pinch & zoom or share the post.

- [ ] Photo uploads should be retried & retries should exponentially backoff until they give up at 30 minutes. After 30 minutes, all posts which failed to upload should have a failed icon over them on the user profile screen & should show the user a tap "retry upload" button. The user should also see an error that the post failed on their home screen. Other posts should continue uploading in parallel so this post does not stop them. 

- [ ] when the verification watermark is enabled, add the posters username to watermark on new line just below “REAL”, and make the entire watermark slightly transparent. This should be the username of the user who originally created the post (not the user sharing it).

- [ ] Real watermark is too big on smaller pictures . 

- [ ] Add option to "privacy & mental health" for "total views" (enable/disable toggle). The backend should still record views, just a user can't query how many views he or someone else with this feature set, has. But the backend will still use total views for recording payouts. The front-end should not be able to query the total views of a user with this property.

- [ ] Followers list seems to be cut off, a bunch of usernames are missing which follow content@real.app for example, doesn't show me as a follower, but I follow that account.

- [ ] Camera should open to selfie mode (mirrored), as instagram's camera does.

- [ ] Bug: When taking a picture using the selfie camera, it's zoomed in for some reason on older phones such as the iphone 8. This does not happen with Instagram or Snapchat when in selfie mode on the same phone/device. 

- [ ] Add mental health setting “Post Verification” (enabled by default): setting to “enabled” (default) will display “Pending Verification” under a post which does not have the is_verified property set to true. This is a backend setting. When this setting is disabled, all followers should not be able to see if a post is verified or not (on the backend). This should disable the post verification status/attribute for the current user & followers via API so that hackers can't see who has disabled this feature. The backend should simulate is_verified = true on all posts response / queries. The backend however will continue to verify all posts and update the is_verified attribute on the backend with the actual real verification status. This property simulates is_verified = true, but keeps the real value in the database for if/when users decide to enable this feature again (all pending posts will show pending). 

- [x] The caption of a post should support emoji’s and show them in the keyboard

- [ ] Pinch & Zoom - Once a user begins to pinch & zoom on an image, the native quality JPEG image (largest filesize) should be downloaded in the background & replaced with the image the user is viewing (zoomed in on) when it completes download. For example, as a user who wants to zoom in on a picture, I pinch & zoom, notice the quality is a bit blurry as I zoom in, but then it clears up after a few seconds while our app is downloading the native quality post in the background. This is a super important feature, as it encourages our users to upload high quality photos (not blurry ones). 

- [ ] post sharing (backend **per post** property) - When disabled, the frontend should hide the share button on this post from followers who see the post in their news feed. This should be enabled by default. This setting should be visible each time a user creates a post (if they want anyone who sees it to be able to share it). This should have subtext "Allows other users to share your posts).

- [ ] Post Sharing (Mental Health Setting). Setting to enabled, shows the option for post sharing (defaulted to true) when creating a post. Setting it to disabled, removes that option (or greys it out) when creating a post. This should have subtext "Allows other users to share your posts).
- [ ] While cropping a photo, you should be able to switch between square & portrait crop while in the crop view. You should also be able to see the overflow greyed out as you can on other platforms so that the user is aware they are cropping the picture, and they are aware of what they cut out.
- [ ] When importing a photo from photo library, the crop should set between Portrait & Square based on the resolution of the photo. If it's closer to our portrait resolution, the cropping should switch to portrait cropping. If the imported photo is closer to square, then the cropping should default to square. 
- [ ] Add iPad support (responsive, portrait only).

- [ ] Deploy app with iPad supported.

- [ ] Add facebook login/signup

- [ ] Add mental health dropdown option "Daily Post Limit" with dropdown options: "Unlimited" default, "10", "20"..."100". Description (heading 2 text under the label/dropdown): "Limit the total number of posts you can see per day.".

- [ ] If a user is hovered on an image which is not yet loaded in the newsfeed (still thumbnail quality), prioritize loading the higher quality version of that image before other images which have not finished loading & may be above it. Skip the queue of images to be downloaded to have the image the user is trying to view (scrolled to) be at the top, so that image is downloaded next. Instagram does this. If I skip to the bottom of my news feed by scrolling quickly, the image/video I land on downloads next.

- [ ] ZenDesk Support https://github.com/Imcloug/REAL-FrontEnd/issues/95

- [ ] Add share location toggle to real posts & store as a post property the location. The location should be the city name. 
- [ ] Finish implementing Comments (when enabled).

- [ ] Add "tap to focus on area" to camera (similar to instagram).

- [ ] Implement allowing the users to transfer their REAL account balance to their PayPal/Braintree account via the PayPal payouts https://developer.paypal.com/docs/payouts/ 

- [ ] Make post preview larger, centered, and allow the user to drag the corners smaller (crop the photo). The crop corners should start in square mode centered on the image. The user can choose to drag each corner fully out to make the photo portrait. 

- [ ] Replace "notifications" section of bottom navigation with a "+" icon. When tapped, the user should have the option to "From Library", "Take Video", "Take Photo", "Text", "Link". Pressing "Text" should allow the user to create a post with a caption, but no video/photo. When a post has no video/photo, only the caption should be shown to other users in the news feed. Pressing "Link" should do the same as "Text" for now. Captions/text should support links/url's inside them. The front end should detect links & allow users to tap them to open the page in their local browser.

- [ ] Apply for Diamond Button - https://github.com/Imcloug/REAL-FrontEnd/issues/99

- [ ] add share to REAL as share option to iOS for movies and photos.

- [ ] Finish Real Chat MVP (will add details)

- [ ] Finish Real Dating MVP (will add details)

- [ ] Redo share icon to match the iOS photos share icon (people don't understand it share). 
https://user-images.githubusercontent.com/3436464/71590882-ff25e000-2ade-11ea-966b-1c5ab7f284e9.png

- [ ] Android support.

**Comment by azimgd** [comment]
Appstore update doesn't work in safari

**Comment by azimgd** [comment]
- remove ```share to instagram as story``` from share screen
- remove ```share to facebook``` from share screen
- repost on real should be visible to other people 
- repost on real should not be visible if shareAllowed = false
- repost ```takenInReal: true``` should be true only if original post is verified
- album title should be visible on post create screen (give priority to text vs thumbnails)
- watermark username display

- photo in album / news feed
- watermark is only visible when post is verified and not dismissed
- refresh user profile when post is uploaded
