### ISSUE TITLE
Backend related

### ISSUE THREAD

**Issue by azimgd** [real-social-media/frontend#2]
- [x] Create a “Dismiss Verification” button to the drop down menu on a post & at the bottom of the learn more page about why your post failed verification. Tapping this button should set a post property (verification_dismissed = true). If this is true, the backend will simulate is_verified = true on the response, but it will keep the actual verification value stored in the database. This way no users can call our API’s to detect & bully users who dismissed verification. 
There should also be a mental health setting which defaults all posts to dismissed 
Similar to how you can enable likes or comments on any post, but the mental health setting sets the default value https://github.com/Imcloug/Selfly-BackEnd/issues/80

- [ ] ability to add watermark to shared photos should not be available unless the post is_verified = true && is_dismissed = false. is_verified should only be allowed to be false for the current user (his followers should see is_verified = true if the current user has is_dismissed = true). The is_dismissed property is private (to a given user). Followers can't see it, but if it's true, the backend shows all followers is_verified = true). **add watermark** should default to greyed out https://github.com/Imcloug/Selfly-BackEnd/issues/79

- [ ] Add description to "verified REAL watermark" which says "Only verified posts can use the REAL watermark", which appears when the user tries to share a post which has is_dismissed=true (this is a private property only the user can see, other users see dismissed posts as is_verified=true). https://github.com/Imcloug/Selfly-BackEnd/issues/79

- [x] Add "Viewed By" to the posts. Only the user who owns the post should ever be able to see the list of people who viewed it. https://github.com/Imcloug/Selfly-BackEnd/issues/92

- [x] Add tag other users support. Having At symbol (can't add it in github without tagging a github user) in a caption should tag the user. Tapping a tag should open the user profile. We should detect & parse the at symbol, followed by all characters until a whitespace using Regex. https://github.com/Imcloug/Selfly-BackEnd/issues/100

- [x] Users should be able to change the expire time in the edit menu. https://github.com/Imcloug/Selfly-BackEnd/issues/96

- [x] Add joined date (date the user joined) to the user profile page. https://github.com/Imcloug/Selfly-BackEnd/issues/91

- [ ] Video post support (using in-app camera & select from iOS library). Videos should be selectable from the iOS library, and can be taken in our camera by holding the take picture button (similar to instagram). We will want to use something like HLS to do this, so we just have 1 video URL and HLS determine the quality/bitrate instead of how we do it for images (thumbnail etc...). Please discuss with Mike & I before implementing. We will need the backend first.
