### ISSUE TITLE
Issues 2/15/2020 (ordered by priority)

### ISSUE THREAD

**Issue by real-ian** [real-social-media/frontend#20]
- [x] Upload from camera library (photos) is broken.
- [x] pressing news feed button should take me to the top of the news feed.
- [x] The app is logging me out frequently (daily), once logged out logging in with google does not work (just loads). 
- [x] Remove camera & chat icons from login screen
- [x] Typing comments which are longer than the text field doesn’t work. Comments text field should allow scrolling, and limit comments to the caption text length limit.
- [x] generate new app certificate for "REAL.app, Inc" as the developer name. 
- [x] Signup is completely broken. After pressing "send confirmation email" the app freezes. Note: the email does send, I just can't enter a code.
- [x] add back settings to user profile
- [x] remove caption on text only posts
- [x] Albums in create post should be limited to 1 line + view more 
- [ ] Test creating an account, making it private, pending follow requests, etc...
- [x] block too many newlines in captions or text only posts (max number of newline characters allowed, or show error)
- [x] show last 3 comments, only show view all comments if there are > 3 
- [x] followers should not be able to see a posts likes or views. Only the post owner can see this. 
- [x] Tapping news feed icon should take the user to the top of the news feed 
- [x] Loading icon should appear while submitting comment, so it appears to instantly
Appear after pressing post comment 
- [x] collapse new post privacy options to make it less cluttered & show the create post button, even when the keyboard is open & the user is creating a caption.
- [x] should be able to watch my own story on news feed by tapping my picture
- [x] sharing for text only posts is broken
- [x] sharing appears in other users posts dropdown, but share does nothing 
- [x] repost in the post share menu does not work
- [x] My profile screen should have posts I just took. Instead I have to refresh it to see posts from the past 10 mins 
- [ ] pinch & zoom + it should support moving while zoomed & download the native quality after the user zooms, to replace it with the photo mid zoom once the download completes. Pinch & Zoom - Once a user begins to pinch & zoom on an image, the native quality JPEG image (largest filesize) should be downloaded in the background & replaced with the image the user is viewing (zoomed in on) when it completes download. For example, as a user who wants to zoom in on a picture, I pinch & zoom, notice the quality is a bit blurry as I zoom in, but then it clears up after a few seconds while our app is downloading the native quality post in the background. This is a super important feature, as it encourages our users to upload high quality photos (not blurry ones). 
- [x] Text only stories don’t seem to be visible as stories.
- [x] Liking posts within trending still is broken 
- [x] Adding from gallery takes me to the camera, it should take me to the photos app gallery directly. 
- [x] Text only posts should not show verification status
- [ ] Should be able to close stories by swiping left/right
- [x] X on search for username is too hard to see on dark theme 
- [x] Tapping the last comment below a post on the news feed should open comments 
- [x] Add "only you can see this" subtext to the views page (the page which shows a list of who viewed a post).
- [x] Viewing stories is broken for me. I just see a black screen when viewing a story
- [ ] The camera is much lower quality & blurrier in our app than in ios camera app, is it possible to improve this?
- [ ] Ask the backend to create an API for viewing comments. When a comment is viewed, create a view record for that comment. A comment view record should only be created on it's first view.
- [ ] Show unseen comments as notification icon “1” on the top right of the user profile icon in the navigation bar. 
- [ ] Show unseen comments as an icon "1" on the top right of posts on the current users profile screen which have unread comments. Those posts should only have a "1" if they were created by the current user & have a new comment, or they have a reply to a comment. This "1" should be dismissed once the user views the comment & creates a view record that he/she has seen that comment. (later we will also implement push notification functionality). 
- [x] The last comment should be visible along with a way to "view all comments". Currently it's hard to tell someone has made a comment. 
- [x] When scrolling down or tapping down news feed & getting close to the bottom, images should load in preparation. Currently, when I reach the bottom I see a loading icon, I then have to tap the right half of a post to scroll down, or scroll down again. 
- [x] Navigation icons are a bit too dark when not selected
- [ ] Text only posts should have a background in the news feed as black / white. If the user has a black theme selected, the text should be white with a black background. If the user has a white/light theme selected, text should be black with a white background on the news feed. The gradient should still be used for thumbnails of text posts.
- [x] Text posts which are small, should take up less of the news feed. For example, 1 line text posts, should take up only 1 line of the news feed (not including username, etc...)
- [x] Fix "failed verification" with new post upload from camera roll method. All posts coming from camera roll in the latest app version are failing for me.
- [ ] Users feel as though their uploads are failing because after 100% upload status, posts can fail to appear in the news feed for a very long time. After creating a post, the frontend should generate a uuid & create the post object locally & put it on the top of the news feed. In the background, the frontend should check Query.post every few seconds until either a timeout, or it sees a success code in the response, then preform a hard refresh. It should also preform a hard refresh if the frontend ever sees the Post.postStatus change to ERROR, which means there is an error processing the image upload. An error (popup) should appear that the post failed to upload and it should be removed from the users news feed. 
- [x] Default comments mental health setting to enabled for new users & existing users. All users posts should have comments enabled (unless after this point, they disable either the comments in the post settings, or mental health settings).
- [x] Push app update to app store
- [x] I see "All posts have been submitted. You can safely close this window now" even while posts are uploading. This text should not be visible until all posts are done uploading. Currently it is always visible. Also, this menu should close itself when all posts are done uploading.
- [x] I can't see stories after creating them for some reason in the latest test flight build (1.2.3.178) https://drive.google.com/file/d/1eswVBbjrZxJR16ZHEhGvH4BWrGg7-Bfq/view?usp=sharing
- [x] When scrolling up/down the news feed, I see a drop in FPS, a little skip/stutter every couple of seconds. I worry this performance issue is caused by albums somehow, although it was not present in the last version which also had albums.
- [x] Can't see my own story on the news feed. For example, when creating a story & tapping my profile icon at the top left of the news feed, I see the camera open. When I have a story, the "+" icon over my profile picture (story) should be replaced with my latest story. 
- [x] Fix sign up issues https://github.com/real-social-media/frontend/issues/22
- [ ] Selecting an album when creating a post is not intuitive if you have more than 2 albums. Users don't know they can scroll left/right on the album slider. If possible, we should really use a dropdown. One of the options in the dropdown should be "Create New Album". **If this is not possible, at the very least, we should limit the albums shown in the current slider to 1 album (the most recent), with "View More" as the 2nd option. This way "View More" is visible. 
- [x] Add expires at time below username when viewing stories 
- [ ] Add support to drag (rearrange) posts in an album to reorder them. 
- [ ] rename "Create Album" in "Albums" to be "New Album +" with a plus sign visible. Also, please move the “Create Album +” button to the top of the page above all existing albums, so the user does not need to scroll to see it. 
- [x] remove "Other" from post dropdown on the news feed. 
- [ ] Fix "Share To Instagram" which is currently broken in 1.2.3.178 https://drive.google.com/file/d/151GrmIIZKX7POxKVru92JeWVrjX5Qgq3/view?usp=sharing
- [ ] Add support for the poster & commenter to delete his/her comment. Currently it appears nobody can delete comments in 1.2.3.178. Note: This may be because I opened the post by searching for the users profile, tapping it, then tapping the post, then comments. 
- [ ] Display the last comment & username of the commenter below the post description.
- [x] Add support to select multiple photos (with check marks) when adding posts from camera roll. When multiple posts are selected and "done" is pressed, each post should trigger a unique "add post" screen for that post, one after another. This will help users when adding many images at once.
- [x] When loading a posts comments, comments from the last viewed post are briefly shown (flashed) 
- [x] Add the ability for the poster to see total views on the bottom right of a post. When tapping this list, the poster should be able to see a list of who viewed the post. Only the poster should be able to see the total or list of who viewed his/her post.
- [x] A user should be able to swipe right/left on posts in the news feed which are inside an album to see other posts. If the Album has > 4 posts, show the first 4 on a carousel, then on the last slide, show the album art with a "View More" button. Tapping "View More" should open the album in the user profile. When tapping the right half of the screen to skip to the next post on the news feed, the next post should be centered in the middle of the screen, even if it’s smaller (square). For example, currently when going up (tapping the left half of the screen), I have to move my thumb up to the top left once I hit a square image in order to continue jumping up. 

- [x] Posts which belong to an album (have a slider in the news feed), should restore back to their default position in the slider if no longer visible. For example, if a user swipes right on a post to view another post in the same album then scrolls down, when scrolling back up, the slider for that post should be back in the default position. This way users don't see duplicate posts when scrolling up.
- [x] Tapping anywhere on the right side of the news feed that isn’t a button should skip to the next post. For example, tapping the bottom right corner (where a thumb feels at rest) should skip as it does on Snapchat. 
- [x] (Bug) When first opening the app and going to my user profile, I can’t tap settings or any posts until I scroll down. This issue is still present in 1.2.3.178. Scrolling "unfreezes" the user profile screen, then I can tap any post or settings. 
- [x] When I reach the bottom of my news feed, I sometimes see infinite loading 
- [x] Discuss new designs with me (Ian) for Albums in news feed (possibly thumbnails of other posts in the same album below a post, but on a slider. Their size & design could mimic the stories design at the top of the news feed.)
- [ ] Discuss new designs with me (Ian) for overlaying captions over posts to help make posts & their captions all fit on the device screen at once (without the user having to scroll to see the caption).
- [x] Fix "Post Membership" screen after pressing "Join Diamond". Currently it looks like this: https://drive.google.com/file/d/1XCklm_lZYP_rJOWiN7CDBdjkgyDwyOiK/view?usp=sharing
- [x] Frozen camera bug, iOS camera is fine but our camera is frozen sometimes. Switching to the iOS camera and then back to our camera unfreezes it. 
- [ ] Store IOS_OTA_VERSION, IOS_APP_STORE_VERSION in a file in S3. **This version file should be checked by the UI every 12 hours**. When the users current version is < the version in that file, either trigger OTA, or if it's the IOS app store version available which is newer, show the user an error "Please update REAL to continue", after tapping OK, the user should be taken to the app store. If the user goes back to our app without updating, they should see the same error. They should not be able to use our app. If the users current version >= IOS_OTA_VERSION && IOS_APP_STORE_VERSION, allow them to use the app. This will help for testing in beta & staging. The OTA check is also important, as users will never close our app or signout. **iOS was designed so you never have to sign out or close apps**. Many of my friends don't even know there is a way to close apps.
- [x] Increase the loading icon time for login with google. Currently the loading icon stops before the login happens, so the user ends up pressing "login with google" a 2nd time, and logging in again. If the user knows to wait, they end up being logged in after about 7-12 seconds on the first attempt. 
- [ ] "Expires in a day/month etc..." should be replaced with the following: If the post expires in <24 hours, it should say "Expires in x hours". If the post expires in 24 hours, it should say "Expires in a day". If the post expires in > 24 hours, it should say "Expires in x days".
- [ ] Add delete option to archived posts, currently users can only “restore from archived” but can’t delete until they restore. 
- [ ] Add confirmation to delete post. This popup should appear for deleting posts in the user profile, new feed, and archived posts. It should say "Are you sure you want to delete this post?"
- [ ] Add the option to share to real from the iOS photos app
- [x] Should be able to view my own story in the news feed. Currently, even if I have a story, I see "+" icon on the top right of the news feed, which opens the camera when tapped.
- [x] Implement REAL Albums https://github.com/real-social-media/frontend/issues/9
- [x] Swipe left while viewing trending post fullscreen, or viewing a post/album should go back.
- [x] Build REAL comments.
- [x] Undo "First Like", after split testing & gathering feedback, people want normal likes back. Please allow **only** the creator of the post to be able to see total likes and who liked his/her post. A total likes count should be visible under the post on the left, along with the username of the last person to like the post. Tapping the post should open a list of who liked it. Please check with Mike that only the creator of the post is able to view total likes & a list of likes. **This should be enforced on the backend for privacy from hackers.** We don't want our users to feel like they need likes because they are queryable by their followers. If the mental health setting is set to disable likes, then total likes should not be visible. Followers should only be able to see the last person to like the post. "Liked by #{username_of_last_like} and many others".
- [x] Text only post support. Users should be able to create a text only post (caption only), with no image/video/audio data. This should be displayed in a responsive way. Depending on the number of characters, this text post should wrap & dynamically change font-size to take up the full height & width of the user device (responsibly) as a picture post would. Text should be white/black with a black/white background (Depending if the user viewing the post has either a dark or light theme selected). This should be visible in the news feed, and user profiles. We should determine a good character limit to keep font sizes from getting too small. 
- [x] Add the users username to the watermark on "shared" photos. Under "REAL" should be the users username on a new line. This should all remain very small on high resolution photos, and only legible when a user zooms in. Important: If a post has the post property origional_post_uuid set, then the username shown in the watermark should be the username of the original poster, not the current user.
- [ ] Video post support. You should be able to select videos in the iOS library, hold the camera button in the in-app camera to take a video, or switch to the mode in the in-app camera which says "Video".
- [x] Clicking "like" on a trending post doesn’t work. 

- [ ] Remove the "remove watermark" option from the share page.
In Payout, replace "business. (e.g Apple Pay, AWS)" with "business (e.g Apple Pay, AWS)."
In Payout, replace "The total post views over the past 30 days from REAL Diamond members of posts created by other REAL Diamond members" with "Total views over the past 30 days of diamond member posts by other REAL diamond members"
Day (Story), Week, Month, Forever 
With footer “All posts will become stories when they are 24 hours from expiring”. All of this should be in the translations file 

- [x] when viewing a profile, it either says "Seems to be empty" or it's blank for 3 seconds until the images appear. **We need a loading icon to instantly appear** when viewing profiles. In testing i've watched people quickly go to someones profile, then back to the news feed, thinking that person has no posts. 
https://user-images.githubusercontent.com/3436464/71771929-65539e00-2ef7-11ea-9ca3-e6171e42a263.png

- [ ] Create front-end deployment script which updates the translations file & deploys a new translations file with the filename as the MD5 of the file. The new front-end should now point to this filename. (This will allow older versions of the front-end to use older translations files). It would also be great to have the front-end swap key-values for all languages which don't match en. now on when I (Ian), edit the local file, I will "find & replace all" swap the key / value for all languages. Because we will have a versioned file, this shouldn't break older versions of the UI. This will all become super important as we grow to support other languages & multiple people are collaborating on the translations github. 

- [x] (Bug) - Users logging in with google for the first time after installing our app, must press "Login with Google", complete the google login flow, are taken back to the login screen, must tap "Login with Google" a 2nd time, they then see a loading icon next to the "Login with Google" button, and are taken into our app. It should all happen in one tap. Note: I had to tap "Login With Google" 5x, and select my email 5x before it worked recently, on a new device. 

- [ ] Center image preview on the "Post Preview" page, and allow users to drag the corners to crop the image. Below the bottom right of the preview, there should also be a square / portrait icon, which snaps the corners to crop the image in that format while keeping the image center. All images should default the crop to the full image size, centered. Cropping an image should keep the original image unmodified in the iOS photo library & not save the rotated image to camera roll, unless the user later decides to download it.

- [ ] Allow users to rotate images in the "Post Preview" page. Rotating should be a slider, so users can rotate the image any desired amount down to the degree. Rotating an image should keep the original image unmodified in the iOS photo library & not save the rotated image to camera roll, unless the user later decides to download it.

- [ ] Add Apple Pay (get diamond) button. https://docs.google.com/document/d/185EGRcI6aPHQvjGqN12InVzRZOqp1ofVkCswswGcfwg/edit?usp=sharing

- [ ] Restrict diamond only features to diamond members only https://docs.google.com/document/d/1JpUly9gC0zZirDC7-Ny0HHhmszMDyc5AI7Ikcd1QCOs/edit?usp=sharing

- [ ] (Feature) Profile link (e.g real.app/username) in any web browser should open our app to that user profile. 

- [ ] (Feature) Post link (e.g real.app/username/post_id) in any web browser should open our app to that user profile.

- [ ] (Feature) Add "Copy Link" to share post options. It should copy the post URL (above) to the iOS clipboard.

- [ ] (Feature) Add "Share Link" to share post options. Tapping this should open the native iOS menu with share options for sharing text (link).

- [ ] (Bug) Fix animation when dragging up/down stories to close them. Currently drag up causes a drap from left to right closing animation. 

- [ ] Swiping up in camera (while the camera is open) should also open photo library to import a photo 

- [ ] (bug) Fix duplicate Signup issue. Content@real.app was created multiple times across user pool & identity pools when using reset password for a user who came from google.

- [ ] Photo uploads should be retried & retries should exponentially backoff until they give up at 30 minutes. After 30 minutes, all posts which failed to upload should have a failed icon over them on the user profile screen & should show the user a tap "retry upload" button. The user should also see an error that the post failed on their home screen. Other posts should continue uploading in parallel so this post does not stop them. 

- [ ] when the verification watermark is enabled, add the posters username to watermark on new line just below “REAL”, and make the entire watermark slightly transparent. This should be the username of the user who originally created the post (not the user sharing it).

- [ ] Real watermark is too big on smaller pictures . 

- [ ] Add option to "privacy & mental health" for "total views" (enable/disable toggle). The backend should still record views, just a user can't query how many views he or someone else with this feature set, has. But the backend will still use total views for recording payouts. The front-end should not be able to query the total views of a user with this property.

- [ ] Followers list seems to be cut off, a bunch of usernames are missing which follow content@real.app for example, doesn't show me as a follower, but I follow that account.

- [ ] Camera should open to selfie mode (mirrored), as instagram's camera does.

- [ ] Bug: When taking a picture using the selfie camera, it's zoomed in for some reason on older phones such as the iphone 8. This does not happen with Instagram or Snapchat when in selfie mode on the same phone/device. 

- [ ] Add mental health setting “Post Verification” (enabled by default): setting to “enabled” (default) will display “Pending Verification” under a post which does not have the is_verified property set to true. This is a backend setting. When this setting is disabled, all followers should not be able to see if a post is verified or not (on the backend). This should disable the post verification status/attribute for the current user & followers via API so that hackers can't see who has disabled this feature. The backend should simulate is_verified = true on all posts response / queries. The backend however will continue to verify all posts and update the is_verified attribute on the backend with the actual real verification status. This property simulates is_verified = true, but keeps the real value in the database for if/when users decide to enable this feature again (all pending posts will show pending). 

- [ ] post sharing (backend **per post** property) - When disabled, the frontend should hide the share button on this post from followers who see the post in their news feed. This should be enabled by default. This setting should be visible each time a user creates a post (if they want anyone who sees it to be able to share it). This should have subtext "Allows other users to share your posts).

- [ ] Post Sharing (Mental Health Setting). Setting to enabled, shows the option for post sharing (defaulted to true) when creating a post. Setting it to disabled, removes that option (or greys it out) when creating a post. This should have subtext "Allows other users to share your posts).
- [ ] While cropping a photo, you should be able to switch between square & portrait crop while in the crop view. You should also be able to see the overflow greyed out as you can on other platforms so that the user is aware they are cropping the picture, and they are aware of what they cut out.
- [ ] When importing a photo from photo library, the crop should set between Portrait & Square based on the resolution of the photo. If it's closer to our portrait resolution, the cropping should switch to portrait cropping. If the imported photo is closer to square, then the cropping should default to square. 
- [ ] Add iPad support (responsive, portrait only).

- [ ] Deploy app with iPad supported.

- [ ] Add facebook login/signup

- [ ] Add mental health dropdown option "Daily Post Limit" with dropdown options: "Unlimited" default, "10", "20"..."100". Description (heading 2 text under the label/dropdown): "Limit the total number of posts you can see per day.".

- [ ] If a user is hovered on an image which is not yet loaded in the newsfeed (still thumbnail quality), prioritize loading the higher quality version of that image before other images which have not finished loading & may be above it. Skip the queue of images to be downloaded to have the image the user is trying to view (scrolled to) be at the top, so that image is downloaded next. Instagram does this. If I skip to the bottom of my news feed by scrolling quickly, the image/video I land on downloads next.

- [ ] ZenDesk Support https://github.com/Imcloug/REAL-FrontEnd/issues/95

- [ ] Add share location toggle to real posts & store as a post property the location. The location should be the city name. 
- [ ] Finish implementing Comments (when enabled).

- [ ] Add "tap to focus on area" to camera (similar to instagram).

- [ ] Implement allowing the users to transfer their REAL account balance to their PayPal/Braintree account via the PayPal payouts https://developer.paypal.com/docs/payouts/ 

- [ ] Make post preview larger, centered, and allow the user to drag the corners smaller (crop the photo). The crop corners should start in square mode centered on the image. The user can choose to drag each corner fully out to make the photo portrait. 

- [ ] Replace "notifications" section of bottom navigation with a "+" icon. When tapped, the user should have the option to "From Library", "Take Video", "Take Photo", "Text", "Link". Pressing "Text" should allow the user to create a post with a caption, but no video/photo. When a post has no video/photo, only the caption should be shown to other users in the news feed. Pressing "Link" should do the same as "Text" for now. Captions/text should support links/url's inside them. The front end should detect links & allow users to tap them to open the page in their local browser.

- [ ] Upload from camera library (photos) is broken 
- [ ] Typing comments which are longer than the text field doesn’t work. Please limit comments to the caption length but allow the text field to scroll.
- [ ] I am being logged out every few times I open the app. When this happens, login with google does nothing (just loads for a few seconds). 
- [ ] The camera & chat icons are visible on the login screen which is confusing.
- [ ] Apply for Diamond Button - https://github.com/Imcloug/REAL-FrontEnd/issues/99

- [ ] add share to REAL as share option to iOS for movies and photos.

- [ ] Finish Real Chat MVP (will add details)
- [ ] Tapping the dropdown on a post, then share, does nothing
- [ ] Viewing my story causes the app to crash in 1.3.0.191. Note, I have a text only post in my story.
- [ ] Finish Real Dating MVP (will add details)

- [ ] Redo share icon to match the iOS photos share icon (people don't understand it share). 
https://user-images.githubusercontent.com/3436464/71590882-ff25e000-2ade-11ea-966b-1c5ab7f284e9.png

- [ ] Android support.
